### PR TITLE
add vendor to ignored folders

### PR DESCRIPTION
**Pull request by dgwyer**
I noticed all the `/vendor/` files/folders were being included so I added them to the ignore list in `.gitignore`.

Note: The following files were automatically modified and added to the PR. Not sure how you handle changes to asset files, and the comoser lock file so I left these in.

- `composer.lock`
- `assets/js/admin/wp-modula-gutenberg.js`

### CODE REVIEW

**Comment by cristianraiber** [comment]
cc @razvanaldea89

**Comment by razvanaldea89** [comment]
Hey @dgwyer ,

Did you recreate the Gutenberg JS file for Modula's block when you've updated some of the dev files from the repo? Don't think that modifying the .gitignore would modify that file also and it may create conflicts / we may launch something that is just in process.

**Comment by razvanaldea89** [comment]
@dgwyer feel free to delete the `remove-vendor-folder` branch if you are not working in it.

**Comment by dgwyer** [comment]
> Will close this PR as it seems that [#807 (comment)](https://github.com/WPChill/modula-lite/pull/807#event-9568852826) already contains the vendor inclusion.

Yeah, added it there too while this PR was reviewed. Redundant now of course now that has been merged.

**Pull request closed without merging**
